feat: single product
hngprojects/hng_boilerplate_csharp_web pull request #121
Opened 2024-07-24 23:18 UTC by droffilc1

# Description

**Closes #86 **

# Changes proposed
- Implement an endpoint to view single product
- Return detailed information on products
- Handle situations where products don't exist

## What were you told to do?
- Create an endpoint /api/v1/products/{product-id} to fetch details of a single product.
- Implement server-side logic to handle successful and failed product retrieval requests.
 - Ensure all sensitive data is encrypted and secure.
 - Implement logging for errors and product retrieval attempts.
 - Write unit tests for the fetch single product endpoint.
 - Write integration tests for the fetch single product logic.
 - Perform security testing to ensure data protection and compliance.

## What did you do?
- Create an endpoint /api/v1/products/{product-id} to fetch details of a single product.
- Implement server-side logic to handle successful and failed product retrieval requests.
 - Ensure all sensitive data is encrypted and secure.
 - Implement logging for errors and product retrieval attempts.
 - Write unit tests for the fetch single product endpoint. 

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/Videos

2024-07-24 23:34 UTC, droffilc1 commented
@dmendie Am failing tests for whitespaces. I can't seem to see it in my editor. Kindly advise.

2024-07-25 07:14 UTC, chimaihueze commented
@droffilc1 kindly run `dotnet format` and it'll format your spaces accordingly.

2024-07-25 07:59 UTC, droffilc1 commented
@chimaihueze I have done that but it seems to fail the check

2024-07-25 08:09 UTC, chimaihueze commented
> @chimaihueze I have done that but it seems to fail the check

- The build error you're encountering now is due to a missing closing brace (}) in the ProductController.cs file at line 51. 

- Also, you have conflicts between different versions of the Microsoft.EntityFrameworkCore.Relational package. 

- Lastly, the title of the pull request, `feat: single product`, does not fully convey the purpose of this feature. For better clarity and to ensure that the title accurately reflects the added functionality, it should be renamed to something more descriptive. I suggest updating the title to "feat: get product by ID".

Fix these.

2024-07-25 09:36 UTC, NdubuisiJr requested changes

2024-07-25 09:36 UTC, NdubuisiJr commented on src/Hng.Application.Test/Features/Products/GetProductByIdQueryShould.cs
> +            _mockMapper = new Mock<IMapper>();
Don't mock IMapper. Take a look at other people's test

2024-07-25 09:36 UTC, NdubuisiJr commented on src/Hng.Application/Features/Products/Dtos/ProductDto.cs
> +        public Guid Id { get; set; }
Use `JsonPropertyName` attribute to turn all your request and response dtos to `snake_case`

2024-07-25 09:36 UTC, NdubuisiJr commented on src/Hng.Application/Features/Products/Handlers/GetProductByIdQueryHandler.cs
> +                throw new KeyNotFoundException($"Product with ID {request.Id} not found.");
Don't throw exceptions. Return null.

2024-07-25 09:36 UTC, NdubuisiJr commented on src/Hng.Infrastructure/Repository/Interface/IRepository.cs
> +        Task<T> GetByIdAsync(Guid id);
Take this none sense out of here. The Repository provides everything for you

2024-07-25 09:36 UTC, NdubuisiJr commented on src/Hng.Infrastructure/Repository/Repository.cs
> +        {
Take this out. Can't you see the method above this does the same thing?

2024-07-25 09:36 UTC, NdubuisiJr commented on src/Hng.Web/Controllers/ProductController.cs
> +    [Route("api/v1/[controller]")]
Don't use conventional naming. write it yourself.

2024-07-25 09:36 UTC, NdubuisiJr commented on src/Hng.Web/Controllers/ProductController.cs
> +            try
Remove all of this try catch

2024-07-25 09:36 UTC, NdubuisiJr commented on src/Hng.Web/Controllers/ProductController.cs
>      [ApiController]
Protect this controller.

2024-07-25 13:54 UTC, NdubuisiJr requested changes

2024-07-25 13:54 UTC, NdubuisiJr commented on src/Hng.Application/Features/Products/Dtos/ProductDto.cs
>          public string description { get; set; }
Don't use camelCase for Properties. Use Normal PascalCasing, then apply `JsonPropertyName` attribute to but it in snake_case

2024-07-25 13:54 UTC, NdubuisiJr commented on src/src.sln
> +﻿
Revert all of the changes to this file

2024-07-25 21:59 UTC, NdubuisiJr requested changes

2024-07-25 21:59 UTC, NdubuisiJr commented on src/src.sln
> +Microsoft Visual Studio Solution File, Format Version 12.00
Delete this file. There's no `src.sln`

2024-07-25 21:59 UTC, NdubuisiJr commented on src/Hng.Web/Controllers/ProductController.cs
> +            return Ok(new { product });
Is this the correct response in the ticket?

2024-07-26 08:57 UTC, NdubuisiJr approved these changes

2024-07-26 08:58 UTC, merged