feat: implemented activate subscription
hngprojects/hng_boilerplate_csharp_web pull request #160
Opened 2024-07-28 21:55 UTC by AlakaTahir

# Description

**Closes #issue_number_here**

# Changes proposed

## What were you told to do?

## What did you do?

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title and description of the PR is clear and explains the approach.
- [ ] I am making a pull request against the **dev branch** (left side).
- [ ] My commit messages styles matches our requested structure.
- [ ] My code additions will fail neither code linting checks nor unit test.
- [ ] I am only making changes to files I was requested to.

# Screenshots/Videos

2024-07-29 14:29 UTC, Ace2489 commented on src/Hng.Application/Features/Subscriptions/Dtos/SubscriptionDto.cs
Snake case for the property names, please

2024-07-29 14:31 UTC, Ace2489 commented
Just a couple of fixes and you should be good to go.

2024-07-29 19:59 UTC, chimaihueze requested changes

2024-07-29 19:59 UTC, chimaihueze commented on src/Hng.Application/Features/Subscriptions/Handlers/ActivateSubscriptionCommandHandler.cs
> +		_subscriptionRepository = subscriptionRepository;
Too much indentation. Please fix this.

2024-07-29 19:59 UTC, chimaihueze commented on src/Hng.Application/Features/Subscriptions/Handlers/ActivateSubscriptionCommandHandler.cs
> +			data.UpdatedAt = DateTime.UtcNow;
Too much indentation. Please fix.

2024-07-29 20:28 UTC, Godhanded requested changes
In your project root directory run
dotnet format --no-restore

to fix all formatting issues automatically

2024-07-30 13:55 UTC, Godhanded requested changes
Okay sweet, please add write ups to the PR template headings are there but no details about what this PR is and what issue it closes, feel free to create the issue if it doesn't already exist on the GitHub.

2024-07-30 21:31 UTC, Godhanded approved these changes

2024-07-30 21:37 UTC, merged