feat(notification): Implement Post Endpoint for Notification Settings
hngprojects/hng_boilerplate_csharp_web pull request #169
Opened 2024-07-29 16:58 UTC by Reliable25

# Description

**Closes #141**

# Changes proposed

## What were you told to do?

Develop and implement the backend components necessary to manage user notification preferences. This includes creating the data models, database schema, API endpoints, and ensuring integration with existing services.
## What did you do?

Design and create a database schema for storing notification preferences.
Develop API endpoints for managing notification settings.
Integrate the notification settings feature with existing user services.
Add authentication to ensure only authenticated users can access the endpoints.

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title and description of the PR is clear and explains the approach.
- [ ] I am making a pull request against the **dev branch** (left side).
- [ ] My commit messages styles matches our requested structure.
- [ ] My code additions will fail neither code linting checks nor unit test.
- [ ] I am only making changes to files I was requested to.

# Screenshots/Videos

2024-07-29 20:23 UTC, Godhanded requested changes

2024-07-29 20:23 UTC, Godhanded commented on src/Hng.Application/Features/Notifications/Commands/CreateNotificationCommand.cs
This file doest seem right, its looking like a dto but this file is for a command

2024-07-30 15:19 UTC, Reliable25 commented on src/Hng.Application/Features/Notifications/Commands/CreateNotificationCommand.cs
have done it, pls check @Godhanded

2024-07-30 19:44 UTC, Godhanded requested changes
this pr is reverting many changes that have already been merged back to before they where, try cloning the repo again and pull to have all the latest changes then add your features and open a pr again

2024-07-30 19:44 UTC, Godhanded commented on src/Hng.Application.Test/Features/UserManagement/GoogleLoginCommandHandlerTests.cs
> +            Assert.Equal("newuser@example.com", result.Data.Email);
Please comment back this line,

2024-07-30 19:44 UTC, Godhanded commented on src/Hng.Application.Test/Features/UserManagement/GetUsersQueryShould.cs
> +                Assert.Contains(expected.LastName, result.Name);
result Full name ,no longer name

2024-07-30 19:44 UTC, Godhanded commented on src/Hng.Application.Test/Features/UserManagement/GetUserByIdQueryShould.cs
> +            Assert.Contains(expected.LastName, result.Name);
result.FullName no longer result.name

2024-07-30 19:44 UTC, Godhanded commented on src/Hng.Application.Test/Features/UserManagement/GoogleLoginCommandHandlerTests.cs
> +            Assert.Equal("existinguser@example.com", result.Data.Email);
Please comment this line again

2024-07-30 19:44 UTC, Godhanded commented on src/Hng.Application.Test/Features/UserManagement/LoginUserCommandShould.cs
> +            Assert.Equal(_user.Email, result.Data.Email);
Comment back this line

2024-07-30 22:34 UTC, closed without merging