Feature/add multiple products main dashboard
hngprojects/hng_boilerplate_csharp_web pull request #219
Opened 2024-08-06 17:24 UTC by AlakaTahir

# Description

Closes #218 

# Changes proposed

## What were you told to do?

I added endpoint to add multiple products

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title and description of the PR is clear and explains the approach.
- [ ] I am making a pull request against the **dev branch** (left side).
- [ ] My commit messages styles matches our requested structure.
- [ ] My code additions will fail neither code linting checks nor unit test.
- [ ] I am only making changes to files I was requested to.

# Screenshots/Videos

2024-08-06 18:18 UTC, chimaihueze requested changes
follow the PR naming standards, and write a detailed description for your PR.

2024-08-06 20:51 UTC, chimaihueze requested changes
Write your unit tests as well.

2024-08-06 20:51 UTC, chimaihueze commented on src/Hng.Web/Controllers/ProductController.cs
> +            var loggedInUserId = HttpContext.User.FindFirst(ClaimTypes.Sid).Value;
There is a service that already does this. Check the AuthenticationService in Infrastructure. You should move whatever logic you want to perform with this to the handler. Keep this controller simple.

2024-08-06 20:51 UTC, chimaihueze commented on src/Hng.Application/Features/Products/Commands/AddProductsCommand.cs
> +        {
This command is for adding Product, it has no business taking userId as a parameter/argument. If you want to assign a user to a product. Do it in the handler.

2024-08-06 21:26 UTC, Godhanded requested changes

2024-08-06 21:26 UTC, Godhanded commented on src/Hng.Application/Features/Products/Commands/AddProductsCommand.cs
> +        public AddProductsCommand(string userId, List<ProductCreationDto> productCreation)
don't collect the userId from the request, use the getloggedinuserId function in authentication service class in hng.infrastructure

2024-08-06 21:26 UTC, Godhanded commented on src/Hng.Application/Features/Products/Handlers/AddProductsHandler .cs
> +                product.UserId = Guid.Parse(request.UserId);
use the GetLoggedInUserId function in hng.infrastructure/services/authenticationservice  to get the id of the user

2024-08-08 09:33 UTC, closed without merging

2024-08-08 09:34 UTC, AlakaTahir commented
Another branch created