/logs route for displaying application logs implementation.
hngprojects/hng_boilerplate_csharp_web pull request #49
Opened 2024-07-19 20:18 UTC by ubongedem78

2024-07-19 21:15 UTC, NdubuisiJr requested changes

2024-07-19 21:15 UTC, NdubuisiJr commented on src/Hng.Web/Program.cs
> +app.UseExceptionHandler(appBuilder =>
@ubongedem78 good work so far. I just have 2 suggestions

- Create an Extension folder, then create a static class, call it `LoggerExtensions`, Create an extension method called `UseGlobalErrorHandler` and move this configuration into that extension method
- Check if the environment is development return the full exception not just the `"An unexpected fault happened. Try again later."` text.

2024-07-19 21:19 UTC, NdubuisiJr requested changes

2024-07-19 21:19 UTC, NdubuisiJr commented on src/Hng.Web/Properties/launchSettings.json
> +  "$schema": "http://json.schemastore.org/launchsettings.json",
Undo all the changes in this file.

2024-07-20 01:38 UTC, NdubuisiJr commented
It looks good now but the app is not building.

2024-07-20 01:39 UTC, NdubuisiJr commented
You are missing a “using” statement for the extension method

2024-07-20 09:48 UTC, ubongedem78 commented
I forgot to push the changes, corrected it now. Thank you @NdubuisiJr.

2024-07-20 15:19 UTC, NdubuisiJr approved these changes

2024-07-20 15:19 UTC, merged